### ISSUE TITLE
Some thoughts... 

### ISSUE THREAD

**Issue by btoplak** [champagnearden/virtualdj-ytm#1]
Hey @champagnearden !

I just found your repo, that's very interesting project you made, congratulations. 

I have some ideas and suggestions that might interest you, but would rather not discuss here. Any other ways to contact you?

**Comment by champagnearden** [comment]
Hey @btoplak !

As you want, we can discuss right here, on discord (champagnearden) or via email (jbbeck42@gmail.com).

I'm happy that my project reached your interest and will be happy to add some features to this project !
